version: '2'
services:
    gestionpfe-app:
        image: gestionpfe
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestionpfe-mysql:3306/gestionpfe?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gestionpfe-mysql:
        extends:
            file: mysql.yml
            service: gestionpfe-mysql
